### ISSUE TITLE
Google fonts manual todo

### ISSUE THREAD

**Issue by rolandwalker** [caskroom/homebrew-fonts#63]
The previous Google Web Font PRs have been generated by working from the mirror at https://github.com/w0ng/googlefontdirectory.

Listed below are 42 fonts remaining (of about 800) which escaped packaging so far.  Not all of these will be Casked in the end, as some are probably duplicates (eg nosifercaps, just looks like a duplicate of `nosifer.rb` from #52).

Others did not have a working homepage, or were missing a `METADATA.json` file -- any oddity which caused them to get dropped by the scripted approach.

- [ ] https://github.com/w0ng/googlefontdirectory/tree/master/fonts/aksarabaligalang
- [ ] https://github.com/w0ng/googlefontdirectory/tree/master/fonts/andadasc
- [ ] https://github.com/w0ng/googlefontdirectory/tree/master/fonts/antonio
- [ ] https://github.com/w0ng/googlefontdirectory/tree/master/fonts/brunoace
- [ ] https://github.com/w0ng/googlefontdirectory/tree/master/fonts/brunoacesc
- [ ] https://github.com/w0ng/googlefontdirectory/tree/master/fonts/butchermancaps
- [x] https://github.com/w0ng/googlefontdirectory/tree/master/fonts/chango
- [x] https://github.com/w0ng/googlefontdirectory/tree/master/fonts/clara
- [ ] https://github.com/w0ng/googlefontdirectory/tree/master/fonts/creepstercaps
- [ ] https://github.com/w0ng/googlefontdirectory/tree/master/fonts/cwtexfangsong
- [ ] https://github.com/w0ng/googlefontdirectory/tree/master/fonts/cwtexhei
- [ ] https://github.com/w0ng/googlefontdirectory/tree/master/fonts/cwtexkai
- [ ] https://github.com/w0ng/googlefontdirectory/tree/master/fonts/cwtexming
- [ ] https://github.com/w0ng/googlefontdirectory/tree/master/fonts/cwtexyen
- [ ] https://github.com/w0ng/googlefontdirectory/tree/master/fonts/eatercaps
- [x] https://github.com/w0ng/googlefontdirectory/tree/master/fonts/hermeneusone
- [x] https://github.com/w0ng/googlefontdirectory/tree/master/fonts/josefinsansstdlight
- [ ] https://github.com/w0ng/googlefontdirectory/tree/master/fonts/lemonone
- [x] https://github.com/w0ng/googlefontdirectory/tree/master/fonts/librecaslontext
- [ ] https://github.com/w0ng/googlefontdirectory/tree/master/fonts/mergeone
- [ ] https://github.com/w0ng/googlefontdirectory/tree/master/fonts/mervalescript
- [x] https://github.com/w0ng/googlefontdirectory/tree/master/fonts/miama
- [ ] https://github.com/w0ng/googlefontdirectory/tree/master/fonts/nosifercaps
- [ ] https://github.com/w0ng/googlefontdirectory/tree/master/fonts/oflsortsmillgoudytt
- [x] https://github.com/w0ng/googlefontdirectory/tree/master/fonts/pecita
- [x] https://github.com/w0ng/googlefontdirectory/tree/master/fonts/poetsenone
- [x] https://github.com/w0ng/googlefontdirectory/tree/master/fonts/portersansblock
- [x] https://github.com/w0ng/googlefontdirectory/tree/master/fonts/redacted
- [x] https://github.com/w0ng/googlefontdirectory/tree/master/fonts/redactedscript
- [ ] https://github.com/w0ng/googlefontdirectory/tree/master/fonts/sansation
- [ ] https://github.com/w0ng/googlefontdirectory/tree/master/fonts/sarabun
- [ ] https://github.com/w0ng/googlefontdirectory/tree/master/fonts/sedan
- [ ] https://github.com/w0ng/googlefontdirectory/tree/master/fonts/sedansc
- [x] https://github.com/w0ng/googlefontdirectory/tree/master/fonts/seoulhangang
- [x] https://github.com/w0ng/googlefontdirectory/tree/master/fonts/seoulhangangcondensed
- [x] https://github.com/w0ng/googlefontdirectory/tree/master/fonts/seoulnamsan
- [x] https://github.com/w0ng/googlefontdirectory/tree/master/fonts/seoulnamsancondensed
- [x] https://github.com/w0ng/googlefontdirectory/tree/master/fonts/seoulnamsanvertical
- [ ] https://github.com/w0ng/googlefontdirectory/tree/master/fonts/strong
- [x] https://github.com/w0ng/googlefontdirectory/tree/master/fonts/terminaldosis
- [x] https://github.com/w0ng/googlefontdirectory/tree/master/fonts/terminaldosislight
- [x] https://github.com/w0ng/googlefontdirectory/tree/master/fonts/tuffy

**Comment by kevinSuttle** [comment]
Well, guess this makes it a little easier. github.com/google/fonts

**Comment by vitorgalvao** [comment]
Repo deleted, so this is no longer relevant.

**Comment by kevinSuttle** [comment]
:hurtrealbad:
